name: Publish (PyPI + MCP Registry)

on:
  workflow_dispatch:

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # REQUIRED for PyPI Trusted Publishing (OIDC)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pipx install uv

      # --- Optional checks (keep for now; can be moved to PR CI later) ---
      - name: Sync deps
        run: uv sync

      - name: Ruff lint
        run: uvx ruff check .

      - name: Ruff format check
        run: uvx ruff format --check .

      - name: Run tests (if present)
        run: |
          if [ -d tests ]; then
            uv run pytest -q
          else
            echo "No tests/ directory; skipping."
          fi

      # --- Build artifacts for PyPI ---
      - name: Build sdist & wheel
        run: uv build

      # --- Publish using Trusted Publishing (no tokens) ---
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          # For a dress rehearsal, you can set:
          # repository-url: https://test.pypi.org/legacy/

  registry:
    name: Publish to MCP Registry
    runs-on: ubuntu-latest
    needs: pypi
    permissions:
      contents: read
      id-token: write  # REQUIRED for MCP Registry GitHub OIDC login
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Small delay to allow PyPI metadata to propagate
      - name: Wait briefly
        run: sleep 20

      - name: Install MCP Publisher
        run: |
          set -e
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
          echo "Get the latest release version"
          LATEST_VERSION=$(curl -s https://api.github.com/repos/modelcontextprotocol/registry/releases/latest | jq -r '.tag_name')
          echo "Installing MCP Publisher version: $LATEST_VERSION"
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/${LATEST_VERSION}/mcp-publisher_${LATEST_VERSION#v}_${OS}_${ARCH}.tar.gz" \
          | tar xz mcp-publisher

      - name: Login to MCP Registry (OIDC)
        run: ./mcp-publisher login github-oidc

      - name: Publish server.json to MCP Registry
        run: ./mcp-publisher publish
